CREATE TABLE ctapp_440ff_export (
    `Detail_key` VARCHAR(22) CHARACTER SET utf8,
    `Detail_properties_Accommodation` INT,
    `Detail_properties_Aft_Deck_m` NUMERIC(4, 1),
    `Detail_properties_Beam_m` NUMERIC(4, 2),
    `Detail_properties_Cargo_Capacity_t` NUMERIC(3, 1),
    `Detail_properties_Classification` VARCHAR(82) CHARACTER SET utf8,
    `Detail_properties_Crane_capacity_t` NUMERIC(3, 2),
    `Detail_properties_Deck_Space_m` NUMERIC(5, 2),
    `Detail_properties_Design` VARCHAR(43) CHARACTER SET utf8,
    `Detail_properties_Engine_Type` VARCHAR(50) CHARACTER SET utf8,
    `Detail_properties_Fender` VARCHAR(14) CHARACTER SET utf8,
    `Detail_properties_Flag` VARCHAR(9) CHARACTER SET utf8,
    `Detail_properties_Forward_Deck_m` NUMERIC(4, 2),
    `Detail_properties_Fresh_Water_Capacity_l` INT,
    `Detail_properties_Fuel_Capacity_l` INT,
    `Detail_properties_Hull_Type` VARCHAR(24) CHARACTER SET utf8,
    `Detail_properties_IMO_Number` VARCHAR(12) CHARACTER SET utf8,
    `Detail_properties_LOA_m` NUMERIC(5, 2),
    `Detail_properties_Last_Port` VARCHAR(13) CHARACTER SET utf8,
    `Detail_properties_MMSI_Number` NUMERIC(10, 1),
    `Detail_properties_Max_Draft_m` NUMERIC(5, 2),
    `Detail_properties_Max_Speed_Kt` NUMERIC(3, 1),
    `Detail_properties_Min_Draft_m` NUMERIC(4, 2),
    `Detail_properties_Number_of_Crew_12hr` INT,
    `Detail_properties_Number_of_Crew_14hr` INT,
    `Detail_properties_Number_of_Crew_24hr` INT,
    `Detail_properties_Number_of_Passengers` INT,
    `Detail_properties_Owner` VARCHAR(46) CHARACTER SET utf8,
    `Detail_properties_Prop_Description` VARCHAR(50) CHARACTER SET utf8,
    `Detail_properties_Prop_Type` VARCHAR(27) CHARACTER SET utf8,
    `Detail_properties_Shipname` VARCHAR(11) CHARACTER SET utf8,
    `Detail_properties_Shipyard` VARCHAR(38) CHARACTER SET utf8,
    `Detail_properties_Transit_Speed_Kt` NUMERIC(3, 1),
    `Detail_properties_Year_of_Construction` INT,
    `Detail_properties_Step_over_distance` INT,
    `News_KgQzRvdpISmfwk179sx_Date` VARCHAR(9) CHARACTER SET utf8,
    `News_KgQzRvdpISmfwk179sx_Headline` VARCHAR(18) CHARACTER SET utf8,
    `News_KgQzRvdpISmfwk179sx_Owner_Name` VARCHAR(8) CHARACTER SET utf8,
    `News_KgQzRvdpISmfwk179sx_Tagged_Vessel` VARCHAR(10) CHARACTER SET utf8,
    `News_KgQzRvdpISmfwk179sx_Text` VARCHAR(88) CHARACTER SET utf8,
    `News_KgQzRvdpISmfwk179sx_owner_Email` VARCHAR(14) CHARACTER SET utf8,
    `News_KgR4pv4J_NFgZnz5mqe_Date` VARCHAR(9) CHARACTER SET utf8,
    `News_KgR4pv4J_NFgZnz5mqe_Headline` VARCHAR(13) CHARACTER SET utf8,
    `News_KgR4pv4J_NFgZnz5mqe_Owner_Name` VARCHAR(8) CHARACTER SET utf8,
    `News_KgR4pv4J_NFgZnz5mqe_Tagged_Vessel` VARCHAR(9) CHARACTER SET utf8,
    `News_KgR4pv4J_NFgZnz5mqe_Text` VARCHAR(73) CHARACTER SET utf8,
    `News_KgR4pv4J_NFgZnz5mqe_owner_Email` VARCHAR(14) CHARACTER SET utf8,
    `News_KgR5Me5R6X0n95QUPVx_Date` VARCHAR(9) CHARACTER SET utf8,
    `News_KgR5Me5R6X0n95QUPVx_Headline` VARCHAR(16) CHARACTER SET utf8,
    `News_KgR5Me5R6X0n95QUPVx_Owner_Name` VARCHAR(8) CHARACTER SET utf8,
    `News_KgR5Me5R6X0n95QUPVx_Tagged_Vessel` VARCHAR(11) CHARACTER SET utf8,
    `News_KgR5Me5R6X0n95QUPVx_Text` VARCHAR(41) CHARACTER SET utf8,
    `News_KgR5Me5R6X0n95QUPVx_owner_Email` VARCHAR(14) CHARACTER SET utf8,
    `News_KgkoIH_N1lj5FNhWO4O_Date` VARCHAR(8) CHARACTER SET utf8,
    `News_KgkoIH_N1lj5FNhWO4O_Headline` VARCHAR(33) CHARACTER SET utf8,
    `News_KgkoIH_N1lj5FNhWO4O_Owner_Name` VARCHAR(8) CHARACTER SET utf8,
    `News_KgkoIH_N1lj5FNhWO4O_Tagged_Vessel` VARCHAR(13) CHARACTER SET utf8,
    `News_KgkoIH_N1lj5FNhWO4O_Text` VARCHAR(424) CHARACTER SET utf8,
    `News_KgkoIH_N1lj5FNhWO4O_owner_Email` VARCHAR(12) CHARACTER SET utf8,
    `News_KhCMrxwPFfmHsPmpkg4_Date` VARCHAR(8) CHARACTER SET utf8,
    `News_KhCMrxwPFfmHsPmpkg4_Headline` VARCHAR(32) CHARACTER SET utf8,
    `News_KhCMrxwPFfmHsPmpkg4_Owner_Name` VARCHAR(8) CHARACTER SET utf8,
    `News_KhCMrxwPFfmHsPmpkg4_Tagged_Vessel` VARCHAR(9) CHARACTER SET utf8,
    `News_KhCMrxwPFfmHsPmpkg4_Text` VARCHAR(121) CHARACTER SET utf8,
    `News_KhCMrxwPFfmHsPmpkg4_owner_Email` VARCHAR(14) CHARACTER SET utf8,
    `News_KhMGwd9nHKkMFmg2Vks_Date` VARCHAR(9) CHARACTER SET utf8,
    `News_KhMGwd9nHKkMFmg2Vks_Headline` VARCHAR(6) CHARACTER SET utf8,
    `News_KhMGwd9nHKkMFmg2Vks_Owner_Name` VARCHAR(8) CHARACTER SET utf8,
    `News_KhMGwd9nHKkMFmg2Vks_Tagged_Vessel` VARCHAR(13) CHARACTER SET utf8,
    `News_KhMGwd9nHKkMFmg2Vks_Text` VARCHAR(33) CHARACTER SET utf8,
    `News_KhMGwd9nHKkMFmg2Vks_owner_Email` VARCHAR(14) CHARACTER SET utf8,
    `News_KhN1pxyra5k0FgV7p01_Date` VARCHAR(9) CHARACTER SET utf8,
    `News_KhN1pxyra5k0FgV7p01_Headline` VARCHAR(6) CHARACTER SET utf8,
    `News_KhN1pxyra5k0FgV7p01_Owner_Name` VARCHAR(8) CHARACTER SET utf8,
    `News_KhN1pxyra5k0FgV7p01_Tagged_Vessel` VARCHAR(13) CHARACTER SET utf8,
    `News_KhN1pxyra5k0FgV7p01_Text` VARCHAR(15) CHARACTER SET utf8,
    `News_KhN1pxyra5k0FgV7p01_owner_Email` VARCHAR(14) CHARACTER SET utf8,
    `Offshore_Wind_Park_key` VARCHAR(38) CHARACTER SET utf8,
    `Offshore_Wind_Park_properties_Lattitude` NUMERIC(6, 4),
    `Offshore_Wind_Park_properties_Longitude` NUMERIC(7, 4),
    `Offshore_Wind_Park_properties_Owner` INT,
    `Owner_key` VARCHAR(47) CHARACTER SET utf8,
    `Owner_properties_Ship_1` VARCHAR(19) CHARACTER SET utf8,
    `Owner_properties_Ship_10` VARCHAR(16) CHARACTER SET utf8,
    `Owner_properties_Ship_2` VARCHAR(20) CHARACTER SET utf8,
    `Owner_properties_Ship_3` VARCHAR(22) CHARACTER SET utf8,
    `Owner_properties_Ship_4` VARCHAR(20) CHARACTER SET utf8,
    `Owner_properties_Ship_5` VARCHAR(18) CHARACTER SET utf8,
    `Owner_properties_Ship_6` VARCHAR(18) CHARACTER SET utf8,
    `Owner_properties_Ship_7` VARCHAR(17) CHARACTER SET utf8,
    `Owner_properties_Ship_8` VARCHAR(20) CHARACTER SET utf8,
    `Owner_properties_Ship_9` VARCHAR(18) CHARACTER SET utf8,
    `Owner_properties_Ship_11` VARCHAR(12) CHARACTER SET utf8,
    `Owner_properties_Ship_12` VARCHAR(16) CHARACTER SET utf8,
    `Owner_properties_Ship_13` VARCHAR(14) CHARACTER SET utf8,
    `Owner_properties_Ship_14` VARCHAR(17) CHARACTER SET utf8,
    `Owner_properties_Ship_15` VARCHAR(13) CHARACTER SET utf8,
    `Owner_properties_Ship_16` VARCHAR(15) CHARACTER SET utf8,
    `Owner_properties_Ship_17` VARCHAR(17) CHARACTER SET utf8,
    `Owner_properties_Ship_18` VARCHAR(12) CHARACTER SET utf8,
    `Owner_properties_Ship_19` VARCHAR(11) CHARACTER SET utf8,
    `Owner_properties_Ship_20` VARCHAR(11) CHARACTER SET utf8,
    `Owner_properties_Ship_21` VARCHAR(12) CHARACTER SET utf8,
    `Owner_properties_Ship_22` VARCHAR(13) CHARACTER SET utf8,
    `Owner_properties_Ship_23` VARCHAR(11) CHARACTER SET utf8,
    `Owner_properties_Ship_24` VARCHAR(14) CHARACTER SET utf8,
    `Owner_properties_Ship_25` VARCHAR(12) CHARACTER SET utf8,
    `Owner_properties_Ship_26` VARCHAR(11) CHARACTER SET utf8,
    `Owner_properties_Ship_27` VARCHAR(10) CHARACTER SET utf8,
    `Owner_properties_Ship_28` VARCHAR(14) CHARACTER SET utf8,
    `Owner_properties_Ship_29` VARCHAR(13) CHARACTER SET utf8,
    `Owner_properties_Ship_30` VARCHAR(11) CHARACTER SET utf8,
    `Owner_properties_Ship_31` VARCHAR(10) CHARACTER SET utf8,
    `Owner_properties_Ship_32` VARCHAR(13) CHARACTER SET utf8,
    `Owner_properties_Ship_33` VARCHAR(12) CHARACTER SET utf8,
    `Owner_properties_Ship_34` VARCHAR(10) CHARACTER SET utf8,
    `Owner_properties_Ship_35` VARCHAR(9) CHARACTER SET utf8,
    `Owner_properties_Ship_36` VARCHAR(9) CHARACTER SET utf8,
    `Owner_properties_Ship_37` VARCHAR(9) CHARACTER SET utf8,
    `Owner_properties_Ship_38` VARCHAR(9) CHARACTER SET utf8,
    `Owner_Accounts_A2Sea_AS_Owner_Email` VARCHAR(14) CHARACTER SET utf8,
    `Owner_Accounts_A2Sea_AS_Owner_Phone` INT,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_10_26_26_Area_of_Operation` VARCHAR(7) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_10_26_26_Date_of_Delivery` DATETIME,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_10_26_26_Date_of_Redelivery` DATETIME,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_10_26_26_Extras_Equipment_Key_0` VARCHAR(6) CHARACTER SET utf8,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_10_26_26_Owner_Name` VARCHAR(8) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_10_26_26_Port_of_Delivery` VARCHAR(7) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_10_26_26_Port_of_Redelivery` VARCHAR(7) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_10_26_26_Scope_of_Work_Key_0` VARCHAR(6) CHARACTER SET utf8,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_10_26_26_Sender_Name` VARCHAR(28) CHARACTER SET utf8,
    `AS_Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_10_26_26_T_C` VARCHAR(15) CHARACTER SET utf8,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_10_26_26_Vessel_MMSI` INT,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_10_26_26_Vessel_Name` VARCHAR(11) CHARACTER SET utf8,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_10_26_26_Working_Hours_per_Day` VARCHAR(3) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_12_46_51_Area_of_Operation` VARCHAR(7) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_12_46_51_Date_of_Delivery` DATETIME,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_12_46_51_Date_of_Redelivery` DATETIME,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_12_46_51_Extras_Equipment_Key_0` VARCHAR(6) CHARACTER SET utf8,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_12_46_51_Owner_Name` VARCHAR(8) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_12_46_51_Port_of_Delivery` VARCHAR(7) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_12_46_51_Port_of_Redelivery` VARCHAR(7) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_12_46_51_Scope_of_Work_Key_0` VARCHAR(6) CHARACTER SET utf8,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_12_46_51_Sender_Name` VARCHAR(28) CHARACTER SET utf8,
    `AS_Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_12_46_51_T_C` VARCHAR(15) CHARACTER SET utf8,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_12_46_51_Vessel_MMSI` INT,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_12_46_51_Vessel_Name` VARCHAR(10) CHARACTER SET utf8,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_12_46_51_Working_Hours_per_Day` VARCHAR(3) CHARACTER SET utf8,
    `Owner_Accounts_A2Sea_AS_Verification_Key` VARCHAR(8) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_21_2_21_Area_of_Operation` VARCHAR(7) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_21_2_21_Date_of_Delivery` DATETIME,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_21_2_21_Date_of_Redelivery` DATETIME,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_21_2_21_Extras_Equipment_Key_0` VARCHAR(6) CHARACTER SET utf8,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_21_2_21_Owner_Name` VARCHAR(10) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_21_2_21_Port_of_Delivery` VARCHAR(7) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_21_2_21_Port_of_Redelivery` VARCHAR(7) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_21_2_21_Scope_of_Work_Key_0` VARCHAR(6) CHARACTER SET utf8,
    `Towage_Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_21_2_21_T_C` VARCHAR(15) CHARACTER SET utf8,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_21_2_21_Vessel_MMSI` INT,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_21_2_21_Vessel_Name` VARCHAR(6) CHARACTER SET utf8,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_21_2_21_Working_Hours_per_Day` VARCHAR(3) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_22_34_26_Area_of_Operation` VARCHAR(7) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_22_34_26_Date_of_Delivery` DATETIME,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_22_34_26_Date_of_Redelivery` DATETIME,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_22_34_26_Extras_Equipment_Key_0` VARCHAR(6) CHARACTER SET utf8,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_22_34_26_Owner_Name` VARCHAR(10) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_22_34_26_Port_of_Delivery` VARCHAR(7) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_22_34_26_Port_of_Redelivery` VARCHAR(7) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_22_34_26_Scope_of_Work_Key_0` VARCHAR(6) CHARACTER SET utf8,
    `Towage_Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_22_34_26_T_C` VARCHAR(15) CHARACTER SET utf8,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_22_34_26_Vessel_MMSI` INT,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_22_34_26_Vessel_Name` VARCHAR(6) CHARACTER SET utf8,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_22_34_26_Working_Hours_per_Day` VARCHAR(3) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_8_12_33_Area_of_Operation` VARCHAR(7) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_8_12_33_Date_of_Delivery` DATETIME,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_8_12_33_Date_of_Redelivery` DATETIME,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_8_12_33_Extras_Equipment_Key_0` VARCHAR(6) CHARACTER SET utf8,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_8_12_33_Owner_Name` VARCHAR(19) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_8_12_33_Port_of_Delivery` VARCHAR(7) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_8_12_33_Port_of_Redelivery` VARCHAR(7) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_8_12_33_Scope_of_Work_Key_0` VARCHAR(6) CHARACTER SET utf8,
    `Towage_Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_8_12_33_T_C` VARCHAR(15) CHARACTER SET utf8,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_8_12_33_Vessel_MMSI` INT,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_8_12_33_Vessel_Name` VARCHAR(6) CHARACTER SET utf8,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_8_12_33_Working_Hours_per_Day` VARCHAR(3) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_9_45_26_Area_of_Operation` VARCHAR(7) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_9_45_26_Date_of_Delivery` DATETIME,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_9_45_26_Date_of_Redelivery` DATETIME,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_9_45_26_Extras_Equipment_Key_0` VARCHAR(20) CHARACTER SET utf8,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_9_45_26_Extras_Equipment_Key_1` VARCHAR(20) CHARACTER SET utf8,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_9_45_26_Owner_Name` VARCHAR(22) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_9_45_26_Port_of_Delivery` VARCHAR(6) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_9_45_26_Port_of_Redelivery` VARCHAR(7) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_9_45_26_Scope_of_Work_Key_0` VARCHAR(12) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_9_45_26_Scope_of_Work_Key_1` VARCHAR(15) CHARACTER SET utf8,
    `BV_Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_9_45_26_Status` VARCHAR(4) CHARACTER SET utf8,
    `BV_Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_9_45_26_T_C` VARCHAR(8) CHARACTER SET utf8,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_9_45_26_Vessel_MMSI` INT,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_9_45_26_Vessel_Name` VARCHAR(8) CHARACTER SET utf8,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_9_45_26_Working_Hours_per_Day` VARCHAR(3) CHARACTER SET utf8,
    `Owner_Accounts_CWind_Ltd_Owner_Email` VARCHAR(10) CHARACTER SET utf8,
    `Owner_Accounts_CWind_Ltd_Owner_Phone` INT,
    `Owner_Accounts_CWind_Ltd_Verification_Key` VARCHAR(8) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_11_43_12_Area_of_Operation` VARCHAR(7) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_11_43_12_Date_of_Delivery` DATETIME,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_11_43_12_Date_of_Redelivery` DATETIME,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_11_43_12_Extras_Equipment_Key_0` VARCHAR(6) CHARACTER SET utf8,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_11_43_12_Owner_Name` VARCHAR(26) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_11_43_12_Port_of_Delivery` VARCHAR(6) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_11_43_12_Port_of_Redelivery` VARCHAR(7) CHARACTER SET utf8,
    `Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_11_43_12_Scope_of_Work_Key_0` VARCHAR(6) CHARACTER SET utf8,
    `GmbH_Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_11_43_12_Status` VARCHAR(4) CHARACTER SET utf8,
    `GmbH_Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_11_43_12_T_C` VARCHAR(15) CHARACTER SET utf8,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_11_43_12_Vessel_MMSI` INT,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_11_43_12_Vessel_Name` VARCHAR(11) CHARACTER SET utf8,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_11_43_12_Working_Hours_per_Day` VARCHAR(3) CHARACTER SET utf8,
    `Ports_key` VARCHAR(50) CHARACTER SET utf8,
    `Ports_properties_Country` VARCHAR(14) CHARACTER SET utf8,
    `Ports_properties_Lattitude` NUMERIC(8, 6),
    `Ports_properties_Longitude` NUMERIC(9, 6),
    `0_2017_5_8_19_15_20_Accepted_by_Owner` VARCHAR(4) CHARACTER SET utf8,
    `0_2017_5_8_19_15_20_Accepted_by_Sender` VARCHAR(4) CHARACTER SET utf8,
    `0_2017_5_8_19_15_20_Additional_information` INT,
    `0_2017_5_8_19_15_20_Area_of_Operation` VARCHAR(14) CHARACTER SET utf8,
    `0_2017_5_8_19_15_20_Date_of_Delivery` DATETIME,
    `0_2017_5_8_19_15_20_Date_of_Redelivery` DATETIME,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_2017_5_8_19_15_20_Day_Rate` INT,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_2017_5_8_19_15_20_Deck_Space_m2` INT,
    `0_2017_5_8_19_15_20_Extras_Equipment_Key_0` VARCHAR(6) CHARACTER SET utf8,
    `Confirmed_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_2017_5_8_19_15_20_LOA_m` INT,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_2017_5_8_19_15_20_Owner_Name` VARCHAR(8) CHARACTER SET utf8,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_2017_5_8_19_15_20_Passengers` INT,
    `0_2017_5_8_19_15_20_Port_of_Delivery` VARCHAR(17) CHARACTER SET utf8,
    `0_2017_5_8_19_15_20_Port_of_Redelivery` VARCHAR(17) CHARACTER SET utf8,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_2017_5_8_19_15_20_Request_ID` VARCHAR(50) CHARACTER SET utf8,
    `0_2017_5_8_19_15_20_Scope_of_Work_Key_0` VARCHAR(6) CHARACTER SET utf8,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_2017_5_8_19_15_20_Sender_Name` VARCHAR(28) CHARACTER SET utf8,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_2017_5_8_19_15_20_Speed_Kt` INT,
    `Confirmed_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_2017_5_8_19_15_20_T_C` VARCHAR(15) CHARACTER SET utf8,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_2017_5_8_19_15_20_Time_Stamp` VARCHAR(8) CHARACTER SET utf8,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_2017_5_8_19_15_20_Vessel_MMSI` INT,
    `CqUtCCSSp5g9Z0s5DesNy9E4af72_0_2017_5_8_19_15_20_Vessel_Name` VARCHAR(10) CHARACTER SET utf8,
    `0_2017_5_8_19_15_20_Working_Hours_per_Day` VARCHAR(3) CHARACTER SET utf8,
    `Data_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_2017_5_8_19_15_20_Owner_Name` INT,
    `Open_Data_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_2017_5_8_19_15_20_T_C` VARCHAR(15) CHARACTER SET utf8,
    `Data_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_2017_5_8_19_15_20_Time_Stamp` VARCHAR(19) CHARACTER SET utf8,
    `Robin_Owner_key` VARCHAR(20) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_1` VARCHAR(19) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_10` VARCHAR(16) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_2` VARCHAR(20) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_3` VARCHAR(22) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_4` VARCHAR(20) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_5` VARCHAR(18) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_6` VARCHAR(18) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_7` VARCHAR(17) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_8` VARCHAR(20) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_9` VARCHAR(18) CHARACTER SET utf8,
    `Robin_Owner_properties_name` VARCHAR(47) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_11` VARCHAR(12) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_12` VARCHAR(16) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_13` VARCHAR(14) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_14` VARCHAR(17) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_15` VARCHAR(13) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_16` VARCHAR(15) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_17` VARCHAR(17) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_18` VARCHAR(12) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_19` VARCHAR(11) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_20` VARCHAR(11) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_21` VARCHAR(12) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_22` VARCHAR(13) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_23` VARCHAR(11) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_24` VARCHAR(14) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_25` VARCHAR(12) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_26` VARCHAR(11) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_27` VARCHAR(10) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_28` VARCHAR(14) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_29` VARCHAR(13) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_30` VARCHAR(11) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_31` VARCHAR(10) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_32` VARCHAR(13) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_33` VARCHAR(12) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_34` VARCHAR(10) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_35` VARCHAR(9) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_36` VARCHAR(9) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_37` VARCHAR(9) CHARACTER SET utf8,
    `Robin_Owner_properties_Ship_38` VARCHAR(9) CHARACTER SET utf8,
    `Robin_offshore_wind_park_key` VARCHAR(20) CHARACTER SET utf8,
    `Robin_offshore_wind_park_properties_Lattitude` NUMERIC(6, 4),
    `Robin_offshore_wind_park_properties_Longitude` NUMERIC(7, 4),
    `Robin_offshore_wind_park_properties_Owner` INT,
    `Robin_offshore_wind_park_properties_name` VARCHAR(38) CHARACTER SET utf8,
    `Robin_ports_key` VARCHAR(20) CHARACTER SET utf8,
    `Robin_ports_properties_Country` VARCHAR(14) CHARACTER SET utf8,
    `Robin_ports_properties_Lattitude` NUMERIC(8, 6),
    `Robin_ports_properties_Longitude` NUMERIC(9, 6),
    `Robin_ports_properties_name` VARCHAR(50) CHARACTER SET utf8,
    `Robin_vessel_specification_key` VARCHAR(20) CHARACTER SET utf8,
    `Robin_vessel_specification_properties_Accommodation` INT,
    `Robin_vessel_specification_properties_Aft_Deck_m` NUMERIC(4, 1),
    `Robin_vessel_specification_properties_Beam_m` NUMERIC(4, 2),
    `Robin_vessel_specification_properties_Cargo_Capacity_t` NUMERIC(3, 1),
    `Robin_vessel_specification_properties_Classification` VARCHAR(82) CHARACTER SET utf8,
    `Robin_vessel_specification_properties_Crane_capacity_t` NUMERIC(3, 2),
    `Robin_vessel_specification_properties_Deck_Space_m` NUMERIC(5, 2),
    `Robin_vessel_specification_properties_Design` VARCHAR(43) CHARACTER SET utf8,
    `Robin_vessel_specification_properties_Engine_Type` VARCHAR(50) CHARACTER SET utf8,
    `Robin_vessel_specification_properties_Fender` VARCHAR(14) CHARACTER SET utf8,
    `Robin_vessel_specification_properties_Flag` VARCHAR(9) CHARACTER SET utf8,
    `Robin_vessel_specification_properties_Forward_Deck_m` NUMERIC(4, 2),
    `Robin_vessel_specification_properties_Fresh_Water_Capacity_l` INT,
    `Robin_vessel_specification_properties_Fuel_Capacity_l` INT,
    `Robin_vessel_specification_properties_Hull_Type` VARCHAR(24) CHARACTER SET utf8,
    `Robin_vessel_specification_properties_IMO_Number` VARCHAR(12) CHARACTER SET utf8,
    `Robin_vessel_specification_properties_LOA_m` NUMERIC(5, 2),
    `Robin_vessel_specification_properties_Last_Port` VARCHAR(13) CHARACTER SET utf8,
    `Robin_vessel_specification_properties_MMSI_Number` INT,
    `Robin_vessel_specification_properties_Max_Draft_m` NUMERIC(5, 2),
    `Robin_vessel_specification_properties_Max_Speed_Kt` NUMERIC(3, 1),
    `Robin_vessel_specification_properties_Min_Draft_m` NUMERIC(4, 2),
    `Robin_vessel_specification_properties_Number_of_Crew_12hr` INT,
    `Robin_vessel_specification_properties_Number_of_Crew_14hr` INT,
    `Robin_vessel_specification_properties_Number_of_Crew_24hr` INT,
    `Robin_vessel_specification_properties_Number_of_Passengers` INT,
    `Robin_vessel_specification_properties_Owner` VARCHAR(46) CHARACTER SET utf8,
    `Robin_vessel_specification_properties_Prop_Description` VARCHAR(50) CHARACTER SET utf8,
    `Robin_vessel_specification_properties_Prop_Type` VARCHAR(27) CHARACTER SET utf8,
    `Robin_vessel_specification_properties_Shipname` VARCHAR(11) CHARACTER SET utf8,
    `Robin_vessel_specification_properties_Shipyard` VARCHAR(38) CHARACTER SET utf8,
    `Robin_vessel_specification_properties_Transit_Speed_Kt` NUMERIC(3, 1),
    `Robin_vessel_specification_properties_Year_of_Construction` INT,
    `Robin_vessel_specification_properties_name` VARCHAR(22) CHARACTER SET utf8,
    `Robin_vessel_specification_properties_Step_over_distance` INT,
    `TableView_key` VARCHAR(22) CHARACTER SET utf8,
    `TableView_properties_Deck_Space_m` NUMERIC(4, 1),
    `TableView_properties_LOA_m` NUMERIC(5, 2),
    `TableView_properties_Max_Speed_Kt` NUMERIC(3, 1),
    `TableView_properties_Number_of_Passengers` INT,
    `TableView_properties_Owner` VARCHAR(40) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_Fleet_ANHOLT_WIND` VARCHAR(8) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_Fleet_Aberdaron_Bay` VARCHAR(25) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_Fleet_Aquata` VARCHAR(9) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_Fleet_Argus_G` VARCHAR(10) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_Fleet_Bayard_1` VARCHAR(30) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_Fleet_Coastal_Flash` VARCHAR(25) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_Fleet_Profiler` VARCHAR(22) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_Fleet_SEA_HURRICANE` VARCHAR(8) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_Fleet_SEA_STORM` VARCHAR(8) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_Fleet_Windea_Four` VARCHAR(26) CHARACTER SET utf8,
    `Request_Open_CqUtCCSSp5g9Z0s5DesNy9E4af72_0_10_26_26_T_C` VARCHAR(15) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_Requests_Confirmed` VARCHAR(23) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_Requests_Market` VARCHAR(3) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_Requests_Vessel` VARCHAR(4) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_Searches_key` VARCHAR(20) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_Searches_properties` VARCHAR(19) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_UserData_Company` VARCHAR(8) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_UserData_Email` VARCHAR(24) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_UserData_Firstname` VARCHAR(5) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_UserData_Lastname` VARCHAR(10) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_UserData_Owner_Email` VARCHAR(14) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_UserData_Owner_Name` VARCHAR(8) CHARACTER SET utf8,
    `User_CqUtCCSSp5g9Z0s5DesNy9E4af72_UserData_Owner_Phone` INT,
    `User_RER3hauxrHN7FrFSOhBuYwedSN82_UserData_Company` VARCHAR(10) CHARACTER SET utf8,
    `User_RER3hauxrHN7FrFSOhBuYwedSN82_UserData_Email` VARCHAR(23) CHARACTER SET utf8,
    `User_RER3hauxrHN7FrFSOhBuYwedSN82_UserData_Firstname` VARCHAR(3) CHARACTER SET utf8,
    `User_RER3hauxrHN7FrFSOhBuYwedSN82_UserData_Lastname` VARCHAR(6) CHARACTER SET utf8,
    `User_X4pGbET2bwgInV5CiN4BJ68jvhq1_Fleet_Coastal_Flash` VARCHAR(25) CHARACTER SET utf8,
    `User_X4pGbET2bwgInV5CiN4BJ68jvhq1_Searches_Kj4Ozt5bvf3adGYueYb` VARCHAR(6) CHARACTER SET utf8,
    `User_X4pGbET2bwgInV5CiN4BJ68jvhq1_Searches_Kj4P0_QJpXMjRbNTkev` VARCHAR(13) CHARACTER SET utf8,
    `User_X4pGbET2bwgInV5CiN4BJ68jvhq1_Searches_KjDOiee2IsBBbvrg633` VARCHAR(6) CHARACTER SET utf8,
    `User_X4pGbET2bwgInV5CiN4BJ68jvhq1_Searches_KjNBM1o6ViV_nwQInEo` VARCHAR(8) CHARACTER SET utf8,
    `User_X4pGbET2bwgInV5CiN4BJ68jvhq1_Searches_KjNBjLs73ogBZJXIZ3t` VARCHAR(13) CHARACTER SET utf8,
    `User_X4pGbET2bwgInV5CiN4BJ68jvhq1_Searches_KjNBoKi47F70x43KOmf` VARCHAR(13) CHARACTER SET utf8,
    `User_X4pGbET2bwgInV5CiN4BJ68jvhq1_Searches_KjNCBIaS17p_C9na7F` VARCHAR(13) CHARACTER SET utf8,
    `User_X4pGbET2bwgInV5CiN4BJ68jvhq1_Searches_KjNCexZQN95PZWKJL7T` VARCHAR(9) CHARACTER SET utf8,
    `User_X4pGbET2bwgInV5CiN4BJ68jvhq1_UserData_Company` VARCHAR(13) CHARACTER SET utf8,
    `User_X4pGbET2bwgInV5CiN4BJ68jvhq1_UserData_Email` VARCHAR(23) CHARACTER SET utf8,
    `User_X4pGbET2bwgInV5CiN4BJ68jvhq1_UserData_Firstname` VARCHAR(5) CHARACTER SET utf8,
    `User_X4pGbET2bwgInV5CiN4BJ68jvhq1_UserData_Lastname` VARCHAR(10) CHARACTER SET utf8,
    `User_X4pGbET2bwgInV5CiN4BJ68jvhq1_UserData_Owner_Email` VARCHAR(14) CHARACTER SET utf8,
    `User_X4pGbET2bwgInV5CiN4BJ68jvhq1_UserData_Owner_Name` VARCHAR(8) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Fleet_Cwind_Advance` VARCHAR(9) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Fleet_KATTEGAT_WIND` VARCHAR(8) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Fleet_MV_Achiever` VARCHAR(29) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Fleet_SEA_GALE` VARCHAR(8) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Fleet_SEA_STORM` VARCHAR(8) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_Kh_F0LEQjoxKu_uLzzy` VARCHAR(10) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_Kh_F6BBb5tTkgyjv8n1` VARCHAR(13) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_Kh_FC50cKT_zKM_j5m7` VARCHAR(13) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_Kh_FG9zVcv_h4k216RM` VARCHAR(13) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_Kh_FJ657OeYvXXjt7lF` VARCHAR(13) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_Kh76SNOYzPTEM8XVg_1` VARCHAR(8) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_KhC7yk3PD_2DDlJsIXr` VARCHAR(8) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_KhCjrwwWfsZzkSA_NVA` VARCHAR(13) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_KhCkFYRY6mGyn_Cx8_3` VARCHAR(11) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_KhDd39htC1R26QpZczx` VARCHAR(13) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_KhDdwNGbhMuSrOqA_wy` VARCHAR(20) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_KhDltaLGqiTTQuop4YL` VARCHAR(10) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_KhDlu8jbSTpBIBmprNH` VARCHAR(11) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_KhDlzzgxTDQ0FGyGN94` VARCHAR(8) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_KhDm02N83XJOhBmpG2x` VARCHAR(9) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_KhDm4BUhAdJ3w4KRRCR` VARCHAR(13) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_KhDo8jNA_glc2xQU6_n` VARCHAR(5) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_KhDoJodoA8_gn6wxE7J` VARCHAR(12) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_KhDoM_TXowkGe5LXRMN` VARCHAR(15) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_KhDoNYOokET_jj5wV63` VARCHAR(13) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_KhDoknYGukDd2hhfRTR` VARCHAR(15) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_KhDonrKH79ZV4ZL8_v0` VARCHAR(15) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_KhDppNhcaBhCqistJNR` VARCHAR(15) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_Ki0OBSiGSQw7Az4M5t6` VARCHAR(5) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_Ki0OE7ZbdmQZ0yTQ5Zk` VARCHAR(9) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_Searches_KiGtxylShADZDvun_kN` VARCHAR(13) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_UserData_Company` VARCHAR(9) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_UserData_Email` VARCHAR(22) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_UserData_Firstname` VARCHAR(6) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_UserData_Lastname` VARCHAR(4) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_UserData_Owner_Email` VARCHAR(10) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_UserData_Owner_Name` VARCHAR(9) CHARACTER SET utf8,
    `User_mUmoZX0mjaeFamHgF1n9yzITH6B2_UserData_Owner_Phone` INT,
    `db_structure_news_some_random_id_generated_by_firebase1_date` INT,
    `structure_news_some_random_id_generated_by_firebase1_description` VARCHAR(36) CHARACTER SET utf8,
    `db_structure_news_some_random_id_generated_by_firebase1_headline` VARCHAR(23) CHARACTER SET utf8,
    `structure_news_some_random_id_generated_by_firebase1_owner_email` VARCHAR(16) CHARACTER SET utf8,
    `structure_news_some_random_id_generated_by_firebase1_owner_name` VARCHAR(12) CHARACTER SET utf8,
    `news_some_random_id_generated_by_firebase1_tagged_vessel` VARCHAR(10) CHARACTER SET utf8,
    `wind_park_some_random_id_generated_by_firebase1_lattitude` INT,
    `wind_park_some_random_id_generated_by_firebase1_longitude` INT,
    `offshore_wind_park_some_random_id_generated_by_firebase1_name` VARCHAR(9) CHARACTER SET utf8,
    `offshore_wind_park_some_random_id_generated_by_firebase1_owner` VARCHAR(14) CHARACTER SET utf8,
    `haseeb_db_structure_owner_KytU5BSfe45tJECg_qm_name` VARCHAR(10) CHARACTER SET utf8,
    `haseeb_db_structure_owner_KytU5BSfe45tJECg_qn_name` VARCHAR(22) CHARACTER SET utf8,
    `db_structure_ports_some_random_id_generated_by_firebase1_country` VARCHAR(7) CHARACTER SET utf8,
    `structure_ports_some_random_id_generated_by_firebase1_lattitude` INT,
    `structure_ports_some_random_id_generated_by_firebase1_longitude` INT,
    `db_structure_ports_some_random_id_generated_by_firebase1_name` VARCHAR(6) CHARACTER SET utf8,
    `requests_all_some_random_id_generated_by_firebase1_created_at` INT,
    `requests_all_some_random_id_generated_by_firebase1_day_rate` INT,
    `requests_all_some_random_id_generated_by_firebase1_deck_size` INT,
    `requests_all_some_random_id_generated_by_firebase1_owner` VARCHAR(37) CHARACTER SET utf8,
    `requests_all_some_random_id_generated_by_firebase1_passenger` INT,
    `all_some_random_id_generated_by_firebase1_port_of_delivery` VARCHAR(5) CHARACTER SET utf8,
    `requests_all_some_random_id_generated_by_firebase1_vessel_name` VARCHAR(7) CHARACTER SET utf8,
    `all_some_random_id_generated_by_firebase1_working_hours_per_day` INT,
    `requests_all_some_random_id_generated_by_firebase2_created_at` INT,
    `requests_all_some_random_id_generated_by_firebase2_day_rate` INT,
    `requests_all_some_random_id_generated_by_firebase2_deck_size` INT,
    `requests_all_some_random_id_generated_by_firebase2_passenger` INT,
    `all_some_random_id_generated_by_firebase2_port_of_delivery` VARCHAR(9) CHARACTER SET utf8,
    `requests_all_some_random_id_generated_by_firebase2_vessel_name` VARCHAR(8) CHARACTER SET utf8,
    `all_some_random_id_generated_by_firebase2_working_hour_per_day` INT,
    `confirmed_some_random_id_generated_by_firebase1_confirmed_at` INT,
    `confirmed_some_random_id_generated_by_firebase1_confirmed_by` VARCHAR(3) CHARACTER SET utf8,
    `requests_confirmed_some_random_id_generated_by_firebase1_status` VARCHAR(9) CHARACTER SET utf8,
    `requests_open_some_random_id_generated_by_firebase2_status` VARCHAR(7) CHARACTER SET utf8,
    `user_some_random_id_generated_by_firebase1_address_city` VARCHAR(7) CHARACTER SET utf8,
    `user_some_random_id_generated_by_firebase1_address_country` VARCHAR(7) CHARACTER SET utf8,
    `user_some_random_id_generated_by_firebase1_address_street` VARCHAR(15) CHARACTER SET utf8,
    `structure_user_some_random_id_generated_by_firebase1_address_zip` INT,
    `structure_user_some_random_id_generated_by_firebase1_created_at` INT,
    `structure_user_some_random_id_generated_by_firebase1_deleted_at` INT,
    `db_structure_user_some_random_id_generated_by_firebase1_email` VARCHAR(15) CHARACTER SET utf8,
    `structure_user_some_random_id_generated_by_firebase1_first_name` VARCHAR(5) CHARACTER SET utf8,
    `structure_user_some_random_id_generated_by_firebase1_last_name` VARCHAR(10) CHARACTER SET utf8,
    `db_structure_user_some_random_id_generated_by_firebase1_password` VARCHAR(18) CHARACTER SET utf8,
    `db_structure_user_some_random_id_generated_by_firebase1_phone` INT,
    `db_structure_user_some_random_id_generated_by_firebase1_status` VARCHAR(6) CHARACTER SET utf8,
    `structure_user_some_random_id_generated_by_firebase1_updated_at` INT,
    `structure_user_some_random_id_generated_by_firebase1_user_type` VARCHAR(5) CHARACTER SET utf8,
    `user_some_random_id_generated_by_firebase2_address_city` VARCHAR(7) CHARACTER SET utf8,
    `user_some_random_id_generated_by_firebase2_address_country` VARCHAR(7) CHARACTER SET utf8,
    `user_some_random_id_generated_by_firebase2_address_street` VARCHAR(11) CHARACTER SET utf8,
    `structure_user_some_random_id_generated_by_firebase2_address_zip` INT,
    `structure_user_some_random_id_generated_by_firebase2_created_at` INT,
    `structure_user_some_random_id_generated_by_firebase2_deleted_at` INT,
    `db_structure_user_some_random_id_generated_by_firebase2_email` VARCHAR(22) CHARACTER SET utf8,
    `structure_user_some_random_id_generated_by_firebase2_first_name` VARCHAR(6) CHARACTER SET utf8,
    `structure_user_some_random_id_generated_by_firebase2_last_name` VARCHAR(4) CHARACTER SET utf8,
    `db_structure_user_some_random_id_generated_by_firebase2_password` VARCHAR(16) CHARACTER SET utf8,
    `db_structure_user_some_random_id_generated_by_firebase2_phone` INT,
    `db_structure_user_some_random_id_generated_by_firebase2_status` VARCHAR(6) CHARACTER SET utf8,
    `structure_user_some_random_id_generated_by_firebase2_updated_at` INT,
    `structure_user_some_random_id_generated_by_firebase2_user_type` VARCHAR(5) CHARACTER SET utf8,
    `some_random_id_generated_by_firebase1_accommodation` INT,
    `specification_some_random_id_generated_by_firebase1_aft_deck_m2` INT,
    `some_random_id_generated_by_firebase1_cargo_capacity` INT,
    `some_random_id_generated_by_firebase1_crane_capacity` INT,
    `specification_some_random_id_generated_by_firebase1_hull_type` VARCHAR(3) CHARACTER SET utf8,
    `specification_some_random_id_generated_by_firebase1_imo_number` INT,
    `specification_some_random_id_generated_by_firebase1_max_draft` INT,
    `specification_some_random_id_generated_by_firebase1_max_speed` INT,
    `specification_some_random_id_generated_by_firebase1_min_draft` INT,
    `specification_some_random_id_generated_by_firebase1_mmsi_number` INT,
    `vessel_specification_some_random_id_generated_by_firebase1_name` VARCHAR(6) CHARACTER SET utf8,
    `specification_some_random_id_generated_by_firebase1_shipyard` VARCHAR(14) CHARACTER SET utf8,
    `some_random_id_generated_by_firebase1_total_crew_12hr` INT,
    `some_random_id_generated_by_firebase1_total_crew_14hr` INT,
    `some_random_id_generated_by_firebase1_total_crew_24hr` INT,
    `some_random_id_generated_by_firebase1_transit_speed` INT
);